// src/components/CellSymbol.vue
<template>
  <span
    class="ttt-symbol"
    :style="cellStyle"
  >
    <svg
      v-if="symbol"
      class="symbol"
    ><use :xlink:href="symbol" /></svg>
  </span>
</template>

<script>
export default {
  name: 'CellSymbol',

  props: {
    index: {
      type: Number,
      required: true,
    },
    value: {
      type: Number,
      required: true,
    },
  },

  computed: {
    symbol() {
      switch (this.value) {
        case 1:
          return '#icon--x'
        case -1:
          return '#icon--circle'
        default:
          return ''
      }
    },

    cellStyle() {
      const color = this.value === -1 ? 'rgba(75, 255, 75, 1)' : 'rgba(5, 5, 255, 1)'
      return `color: ${color};`
    },
  },
}
</script>

// src/components/CellSymbol.jsx
import React from 'react'

function getSymbol(value) {
  switch (value) {
    case 1:
      return '#icon--x'
    case -1:
      return '#icon--circle'
    default:
      return ''
  }
}

export default function CellSymbol({ index, value }) {
  const symbol = getSymbol(value)
  const color = value === -1 ? 'rgba(75, 255, 75, 1)' : 'rgba(5, 5, 255, 1)'

  return (
    <span
      className="ttt-symbol"
      data-index={index}
      style={{ color }}
    >
      {symbol ? (
        <svg className="symbol">
          <use href={symbol} />
        </svg>
      ) : null}
    </span>
  )
}
